let domain="";

 domain = "http://192.168.10.200:8080/";
// domain = "http://49.248.147.178:8082/";
  

export const APIURL = {
  ListOfDirectoryFromFTP:domain+"api/Common/ListOfDirectoryFromFTP", 
  ListOfFilesFromFTP:domain+"api/Common/ListOfFilesFromFTP",
  FileDownload: domain + "api/Common/FileDownload",
  FTPUPLOAD: domain + "api/Common/FileUpload",
  FTPFILELIST: domain + "api/Common/ListOfFilesFromFTP",
  DELETEFTPFILE:domain+"api/Common/DeleteFileFromFTP",
  Login: domain + "api/users/login",
  Logout: domain + "api/users/Logout",
  GetAllIncoTerms:domain+"api/Common/GetAllIncoTerms",

  addNewCompany: domain + "api/Company/CreateCompany",
  GetCompanies: domain + "api/Company/GetCompanies",
  GetCompany: domain + "api/Company/GetCompany",
  UpdateCompany: domain + "api/Company/UpdateCompany",
  getTempData: domain + "api/TempData/getTempData",
  DeleteCompany: domain + "api/Company/DeleteCompany",
  GetCountries: domain + "api/Country/GetCountries",
  CreateCountry: domain + "api/Country/CreateCountry",
  DeleteCountry: domain + "api/Country/DeleteCountry",
  UpdateCountry: domain + "api/Country/UpdateCountry",
  GetCountry: domain + "api/Country/GetCountry",
  GetZones: domain + "api/Zone/GetZones",
  GetState: domain + "api/State/GetState",
  GetStateByCountryId: domain + "api/State/GetStateByCountryId",
  GetStates: domain + "api/State/GetStates",
  CreateState: domain + "api/State/CreateState",
  UpdateState: domain + "api/State/UpdateState",
  GetDestinationByCountryId: domain + "api/Destination/GetDestinationByCountryId",
  GetDestinations: domain + "api/Destination/GetDestinations",
  GetDestination: domain + "api/Destination/GetDestination",
  UpdateDestination: domain + "api/Destination/UpdateDestination",
  CreateDestination: domain + "api/Destination/CreateDestination",
  GetDestinationByCountryIdAndStateId: domain + "api/Destination/GetDestinationByCountryIdAndStateId",
  GetUsers: domain + "api/users/GetUsers",
  AddUser: domain + "api/users/CreateUser",
  GetUser: domain + "api/users/GetUser",
  UpdateUser: domain + "api/users/UpdateUser",
  GetBraches: domain + "api/Branch/GetBraches",  
  GetBranch: domain + "api/Branch/GetBranch",
  UpdateBranch: domain + "api/Branch/UpdateBranch",
  CreateBranch: domain + "api/Branch/CreateBranch",
  CreateBranchLicenseDetail:domain+"api/BranchLicenseDetail/CreateBranchLicenseDetail",
  UpdateBranchLicenseDetail:domain+"api/BranchLicenseDetail/UpdateBranchLicenseDetail",
  CreateBranchOtherCharges:domain+"api/Branch/CreateBranchOtherCharges",
  UpdateBranchOtherCharges:domain+"api/Branch/UpdateBranchOtherCharges",
  GetBranchLicenseDetail:domain+"api/BranchLicenseDetail/GetBranchLicenseDetail",
  GetBranchOtherChargesByBranchID:domain+"api/Branch/GetBranchOtherChargesByBranchID",
  GetBranchOtherChargesByID:domain+"api/Branch/GetBranchOtherChargesByID",
  CreateUserBranchMapping: domain + "api/UserBranchMapping/CreateUserBranchMapping",
  GetUserBranchMappedByUserID: domain + "api/UserBranchMapping/GetUserBranchMappedByUserID",
  CreateModule: domain + "api/Module/CreateModule",
  UpdateModule: domain + "api/Module/UpdateModule",
  GetModules: domain + "api/Module/GetModules",
  GetModule: domain + "api/Module/GetModule",
  CreatePage: domain + "api/Page/CreatePage",
  GetPages: domain + "api/Page/GetPages",
  GetPageByModuleId: domain + "api/Page/GetPageByModuleId",
  UpdatePage: domain + "api/Page/UpdatePage",
  UpdateModuleIdByPageID: domain + "api/Page/UpdateModuleIdByPageID",
  UpdatePageByModuleIdAndPageID: domain + "api/Page/UpdatePageByModuleIdAndPageID",
  GetRoles: domain + "api/Role/GetRoles",
  CreateRole: domain + "api/Role/CreateRole",
  GetRoleDetailByRoleId: domain + "api/RoleDetail/GetRoleDetailByRoleId",
  CreateRoleDetail: domain + "api/RoleDetail/CreateRoleDetail",
  GetAllUserPermission: domain + "api/UserPermission/GetAllUserPermission",
  GetUserPermissionByUserIDAndBranchID: domain + "api/UserPermission/GetUserPermissionByUserIDAndBranchID",
  CreateUserPermission: domain + "api/UserPermission/CreateUserPermission",
  GetUserPermissionByRoleId: domain + "api/UserPermission/GetUserPermissionByRoleId",
  GetWareHouses: domain + "api/WareHouse/GetWareHouses",
  GetWareHouseByBranchID:domain +"api/WareHouse/GetWareHouseByBranchID",
  CreateWareHouse: domain + "api/WareHouse/CreateWareHouse",
  UpdateWareHouse: domain + "api/WareHouse/UpdateWareHouse",
  GetWareHouse: domain + "api/WareHouse/GetWareHouse",
  GetCurrencies: domain + "api/Currency/GetCurrencies",
  CreateCurrency: domain + "api/Currency/CreateCurrency",
  CreateNoSeries: domain + "api/NoSeriesDetails/CreateNoSeries",
  
  GetNoSeriesByNoSeriesId: domain + "api/NoSeriesDetails/GetNoSeriesByNoSeriesId",
  UpdateNoSeries: domain + "api/NoSeriesDetails/UpdateNoSeries",
  CreateItem: domain + "api/ItemMaster/CreateItem",
  UpdateItem: domain + "api/ItemMaster/UpdateItem",
  GetAllItems: domain + "api/ItemMaster/GetAllItems",
  GetItem: domain + "api/ItemMaster/GetItem",
  GetItemsSalesPriceByBranchID:domain+"api/Sales/GetItemsSalesPriceByBranchID",
  Add_Update_ItemsSalesPrice:domain+"api/Sales/Add_Update_ItemsSalesPrice",
  GetItemsStandardCostByID:domain+"api/ItemMaster/GetItemsStandardCostByID",
  Add_Update_ItemsStandardCost:domain+"api/ItemMaster/Add_Update_ItemsStandardCost",
  GetGSTGroup:domain+"api/Taxation/GetGSTGroup",
  CreateItemDepartment: domain + "api/ItemMaster/CreateItemDepartment",
  GetItemDepartments: domain + "api/ItemMaster/GetItemDepartments",
  GetItemDepartment: domain + "api/ItemMaster/GetItemDepartment",
  UpdateItemDepartment: domain + "api/ItemMaster/UpdateItemDepartment",
  UpdateItemSuperCategoryRestrictedBranch:domain+"api/ItemMaster/UpdateItemSuperCategoryRestrictedBranch",
  CreateItemSuperCategory: domain + "api/ItemMaster/CreateItemSuperCategory",
  GetItemSuperCategories: domain + "api/ItemMaster/GetItemSuperCategories",
  GetItemSuperCategory: domain + "api/ItemMaster/GetItemSuperCategory",
  UpdateItemSuperCategory: domain + "api/ItemMaster/UpdateItemSuperCategory",
  GetItemSuperCategoryRestrictedBranchID:domain+"api/ItemMaster/GetItemSuperCategoryRestrictedBranchID",
  CreateItemMainCategory: domain + "api/ItemMaster/CreateItemMainCategory",
  GetItemMainCategories: domain + "api/ItemMaster/GetItemMainCategories",
  GetItemMainCategory: domain + "api/ItemMaster/GetItemMainCategory",
  UpdateItemMainCategory: domain + "api/ItemMaster/UpdateItemMainCategory",
  CreateItemCategory: domain + "api/ItemMaster/CreateItemCategory",
  GetItemCategories: domain + "api/ItemMaster/GetItemCategories",
  GetItemCategory: domain + "api/ItemMaster/GetItemCategory",
  UpdateItemCategory: domain + "api/ItemMaster/UpdateItemCategory",
  GetItemTypeByCatID: domain + "api/ItemMaster/GetItemTypeByCatID",
  CreateItemPostingGroup: domain + "api/Posting/CreateItemPostingGroup",
  GetAllItemPostingGroup: domain + "api/Posting/GetAllItemPostingGroup",
  UpdateItemPostingGroup: domain + "api/Posting/UpdateItemPostingGroup",
  GetAllGeneralPostingGroup: domain + "api/Posting/GetAllGeneralPostingGroup",
  CreateGeneralPostingGroup: domain + "api/Posting/CreateGeneralPostingGroup",
  UpdateGeneralPostingGroup: domain + "api/Posting/UpdateGeneralPostingGroup",
  CreateCustomerPostingGroup: domain + "api/Posting/CreateCustomerPostingGroup",
  CreateSupplierPostingGroup: domain + "api/Posting/CreateSupplierPostingGroup",
  GetAllSupplierPostingGroup: domain + "api/Posting/GetAllSupplierPostingGroup",
  GetAllCustomerPostingGroup: domain + "api/Posting/GetAllCustomerPostingGroup",
  CreateChartOfAccount: domain + "api/ChartOfAccount/CreateChartOfAccount",
  GetChartOfAccounts: domain + "api/ChartOfAccount/GetChartOfAccounts",
  GetChartOfAccount: domain + "api/ChartOfAccount/GetChartOfAccount",
  UpdateChartOfAccount: domain + "api/ChartOfAccount/UpdateChartOfAccount",
  CreateCustomer: domain + "api/Customer/CreateCustomer",
  GetAllCustomer: domain + "api/Customer/GetAllCustomer",
  GetCustomer: domain + "api/Customer/GetCustomer",
  UpdateCustomer: domain + "api/Customer/UpdateCustomer",
  GetAllCustomerContact: domain + "api/Customer/GetAllCustomerContact",
  CreateCustomerContact: domain + "api/Customer/CreateCustomerContact",
  GetCustomerContact: domain + "api/Customer/GetCustomerContact",
  CreateCustomerAddress: domain + "api/Customer/CreateCustomerAddress",
  GetAllCustomerAddress: domain + "api/Customer/GetAllCustomerAddress",
  GetCustomerAddress: domain + "api/Customer/GetCustomerAddress",
  GetAllCustomerAddressByCustID: domain + "api/Customer/GetAllCustomerAddressByCustID",
  GetAllCustomerContactByCustID: domain + "api/Customer/GetAllCustomerContactByCustID",
  UpdateCustomerAddress: domain + "api/Customer/UpdateCustomerAddress",
  UpdateCustomerContact: domain + "api/Customer/UpdateCustomerContact",
  GetAllPaymentTerms: domain + "api/Customer/GetAllPaymentTerms",
  CreatePaymentTerms: domain + "api/Customer/CreatePaymentTerms",
  UpdatePaymentTerms: domain + "api/Customer/UpdatePaymentTerms",
  GetAllCustomerCategory: domain + "api/Customer/GetAllCustomerCategory",
  CreateCustomerCategory: domain + "api/Customer/CreateCustomerCategory",
  UpdateCustomerCategory: domain + "api/Customer/UpdateCustomerCategory",
  GetCustomerSlabDiscountByCustID:domain+"api/Customer/GetCustomerSlabDiscountByCustID",
  CreateCustomerSlabDiscount:domain+"api/Customer/CreateCustomerSlabDiscount",
  GetGeneralSlabDiscountByBranchID:domain+"api/Common/GetGeneralSlabDiscountByBranchID",
  Add_Update_GeneralSlabDiscount:domain+"api/Common/Add_Update_GeneralSlabDiscount",
  GetAllSalesPerson: domain + "api/Customer/GetAllSalesPerson",
  UpdateSalesPerson: domain + "api/Customer/UpdateSalesPerson",
  GetAllUOM: domain + "api/Common/GetAllUOM",
  GetSpecification:domain + "api/Common/GetSpecification",
  Add_UpdateCustomerPrice: domain + "api/Customer/Add_UpdateCustomerPrice",
  GetCustomerPriceByCustID: domain + "api/Customer/GetCustomerPriceByCustID",
  CreateCustomerBranchMapping: domain + "api/Customer/CreateCustomerBranchMapping",
  GetCustomerBranchMappingByCustID: domain + "api/Customer/GetCustomerBranchMappingByCustID",
  GetAllSupplier: domain + "api/Supplier/GetAllSupplier",
  UpdateSupplier: domain + "api/Supplier/UpdateSupplier",
  CreateSupplier: domain + "api/Supplier/CreateSupplier",
  GetSupplier: domain + "api/Supplier/GetSupplier",
  GetSuppliersByBranchID:domain + "api/Supplier/GetSuppliersByBranchID",
  GetAllNoSeriesByBranchId: domain + "api/NoSeriesDetails/GetAllNoSeriesByBranchId",
  GetMasterDocumentNumber: domain + "api/Common/GetMasterDocumentNumber",
  GetDocumentNumber: domain +"api/Common/GetDocumentNumber",
  CreateSupplierBranchMapping: domain + "api/Supplier/CreateSupplierBranchMapping",
  GetSupplierBranchMappingBySuplID: domain + "api/Supplier/GetSupplierBranchMappingBySuplID",
  GetAllSupplierAddressBySuplID: domain + "api/Supplier/GetAllSupplierAddressBySuplID",
  CreateSupplierAddress: domain + "api/Supplier/CreateSupplierAddress",
  UpdateSupplierAddress: domain + "api/Supplier/UpdateSupplierAddress",
  GetSupplierAddress: domain + "api/Supplier/GetSupplierAddress",
  Add_UpdateSupplierPrice: domain + "api/Supplier/Add_UpdateSupplierPrice",
  GetSupplierPriceBySuplID: domain + "api/Supplier/GetSupplierPriceBySuplID",
  GetMODTax:domain +"api/Common/GetMODTax",
  GetShipmentMode:domain+"api/Common/GetShipmentMode",
  GetDimensions:domain+"api/Dimension/GetDimensions",
  Add_Update_PO:domain+"api/PO/Add_Update_PO",
  GetPOByBranchID:domain+"api/PO/GetPOByBranchID",
  GetPOByPOID:domain+"api/PO/GetPOByPOID",
  Add_Update_PurchaseOrderAuthorize:domain+"api/PO/Add_Update_PurchaseOrderAuthorize",
  Add_Update_MRN:domain+"api/PO/Add_Update_MRN",
  GetMRNByBranchID:domain+"api/PO/GetMRNByBranchID",
  GetMRNByMRNID:domain+"api/PO/GetMRNByMRNID",
  MRN_Post:domain+"api/po/MRN_Post",
  Add_Update_GIT:domain+"api/PO/Add_Update_GIT",
  GetGITByBranchID:domain+"api/PO/GetGITByBranchID",
  GetGITByGITID:domain+"api/PO/GetGITByGITID",
  GITAuthorize:domain+"api/PO/GITAuthorize",
  GetPIByBranchID:domain+"api/PO/GetPIByBranchID",
  GetMRNBySuplID:domain+"api/PO/GetMRNBySuplID",
  Add_Update_PI:domain+"api/PO/Add_Update_PI",
  GetPIByPIID:domain+"api/PO/GetPIByPIID",
  PI_Post:domain+"api/po/PI_Post",
  GetPIVoucherByPIID:domain+"api/po/GetPIVoucherByPIID",
  GetProformaInvoiceByBranchID:domain+"api/Sales/GetProformaInvoiceByBranchID",
  GetCustomersByBranchID:domain+"api/Sales/GetCustomersByBranchID",
  Add_Update_ProformaInvoice:domain+"api/Sales/Add_Update_ProformaInvoice",
  GetProformaInvoiceByProformaID:domain+"api/Sales/GetProformaInvoiceByProformaID",
  GetSalesOrderByBranchID:domain+"api/Sales/GetSalesOrderByBranchID",
  Add_Update_SalesOrder:domain+"api/Sales/Add_Update_SalesOrder",
  GetSalesOrderBySOID:domain+"api/Sales/GetSalesOrderBySOID",
  GetSalesRequestByBranchID:domain+"api/Sales/GetSalesRequestByBranchID",
  GetSalesRequestByRequestID:domain+"api/Sales/GetSalesRequestByRequestID",
  Add_Update_SalesRequest:domain+"api/Sales/Add_Update_SalesRequest",
  SOforSRGetByBranchID:domain+"api/Sales/SOforSRGetByBranchID",
  Add_Update_SalesInvoice:domain+"api/Sales/Add_Update_SalesInvoice",
  GetSalesInvoiceByBranchID:domain+"api/Sales/GetSalesInvoiceByBranchID",
  GetSalesInvoiceBySIID:domain+"api/Sales/GetSalesInvoiceBySIID",
  SalesInvoicePost:domain+"api/Sales/SalesInvoicePost",
  GetSOForSIByBranchID:domain+"api/Sales/GetSOForSIByBranchID",
  SalesOrderToIJC:domain+"api/Sales/SalesOrderToIJC",
  GetIJCByBranchID:domain+"api/Sales/GetIJCByBranchID",
  GetIJCByIJCID:domain+"api/Sales/GetIJCByIJCID",
  Add_update_IJC:domain+"api/Sales/Add_update_IJC",
  GetProductionByBranchID:domain+"api/Production/GetProductionByBranchID",
  Add_Update_Production:domain+"api/Production/Add_Update_Production",
  GetProductionByDPID:domain+"api/Production/GetProductionByDPID",
  Add_Update_ItemPostingGroup:domain+"api/Posting/Add_Update_ItemPostingGroup",
  Add_Update_GeneralPostingGroup:domain+"api/Posting/Add_Update_GeneralPostingGroup",
  Add_Update_SupplierPostingGroup:domain+"api/Posting/Add_Update_SupplierPostingGroup",
  Add_Update_GeneralPostingGroupSetup:domain+"api/Posting/Add_Update_GeneralPostingGroupSetup",
  GetAllGeneralPostingGroupSetup:domain+"api/Posting/GetAllGeneralPostingGroupSetup",
  Add_Update_CustomerPostingGroup:domain+"api/Posting/Add_Update_CustomerPostingGroup",
  GetAllGSTSetup:domain+"api/Posting/GetAllGSTSetup",
  Add_Update_GSTSetup:domain+"api/Posting/Add_Update_GSTSetup",
  GetAllGSTSetup:domain+"api/Posting/GetAllGSTSetup",
  GetAllVATSetup:domain+"api/Posting/GetAllVATSetup",
  Add_Update_VATSetup:domain+"api/Posting/Add_Update_VATSetup",
  Add_Update_StoreRequisition:domain+"api/Stores/Add_Update_StoreRequisition",
  GetStoreRequisitionByBranchID:domain+"api/Stores/GetStoreRequisitionByBranchID",
  GetStoreRequisitionByRequID:domain+"api/Stores/GetStoreRequisitionByRequID",
  UpdateStoreRequisitionAuthorize:domain+"api/Stores/UpdateStoreRequisitionAuthorize",
  GetGeneralDetailsByBranchID:domain+"api/Common/GetGeneralDetailsByBranchID",
  GetStoreIssueByBranchID:domain+"api/Stores/GetStoreIssueByBranchID",
  GetStoreIssueByIssueID:domain+"api/Stores/GetStoreIssueByIssueID",
  Add_Update_StoreIssue:domain+"api/Stores/Add_Update_StoreIssue",
  StoreIssue_Post:domain+"api/Stores/StoreIssue_Post",
  GetCreditNoteByBranchID:domain+"api/Accounts/GetCreditNoteByBranchID",
  Add_Update_CreditNote:domain+"api/Accounts/Add_Update_CreditNote",
  GetSIAndPIByBranchID:domain+"api/Sales/GetSIAndPIByBranchID",
  GetCreditNoteByCNID:domain+"api/Accounts/GetCreditNoteByCNID",
  GetDebitNoteByBranchID:domain+"api/Accounts/GetDebitNoteByBranchID",
  Add_Update_DebitNote:domain+"api/Accounts/Add_Update_DebitNote",
  GetDebitNoteByDNID:domain+"api/Accounts/GetDebitNoteByDNID",
  GetCashByBranchID:domain+"api/Cash/GetCashByBranchID",
  Add_Update_Cash:domain+"api/Cash/Add_Update_Cash",
  GetCashByID:domain+"api/Cash/GetCashByID",
  GetBankByBranchID:domain+"api/Bank/GetBankByBranchID",
  GetBankByID:domain+"api/Bank/GetBankByID",
  Add_Update_Bank:domain+"api/Bank/Add_Update_Bank",
  DebitCreditPost:domain+"api/Accounts/DebitCreditPost",
  GetVoucherByBranchID:domain+"api/Accounts/GetVoucherByBranchID",
  GetJournalVoucherByBranchID:domain+"api/Accounts/GetJournalVoucherByBranchID",
  Add_Update_JournalVoucher:domain+"api/Accounts/Add_Update_JournalVoucher",
  GetJournalVoucherByJVID:domain+"api/Accounts/GetJournalVoucherByJVID",
  GetJournalVoucherPost:domain+"api/Accounts/GetJournalVoucherPost",
  GetPaymentVoucherByBranchID:domain+"api/Accounts/GetPaymentVoucherByBranchID",
  GetPaymentVoucherByPVID:domain+"api/Accounts/GetPaymentVoucherByPVID",
  Add_update_Payment:domain+"api/Accounts/Add_update_Payment",
  PaymentPost:domain+"api/Accounts/PaymentPost",
  GetReceiptByBranchID:domain+"api/Accounts/GetReceiptByBranchID",
  Add_Update_Receipt:domain+"api/Accounts/Add_Update_Receipt",
  GetReceiptByRVID:domain+"api/Accounts/GetReceiptByRVID",
  ReceiptPost:domain+"api/Accounts/ReceiptPost",
  GetContraByBranchID:domain+"api/Accounts/GetContraByBranchID",
  Add_Update_Contra:domain+"api/Accounts/Add_Update_Contra",
  GetContraByCEID:domain+"api/Accounts/GetContraByCEID",
  ContraPost:domain+"api/Accounts/ContraPost",
  GetGLLedgerEntryByBranchID:domain+"api/Accounts/GetGLLedgerEntryByBranchID",
  Add_Update_GateEntry:domain+"api/Common/Add_Update_GateEntry",
  UserNotificationTokenUpdate:domain+"api/Users/UserNotificationTokenUpdate",

  E_GST:{
    GetToken:"https://gstsandbox.charteredinfo.com/eivital/dec/v1.04/auth",
  },
};